#!/bin/bash
iteration=3
work_duration=25
rest_duration=5

countdown()
(
  IFS=:
  set -- $*
  secs=$1
  while [ $secs -gt 0 ]
  do
    sleep 1 &
    printf "\r%02d:%02d:%02d" $((secs/3600)) $(( (secs/60)%60)) $((secs%60))
    secs=$(( $secs - 1 ))
    wait
  done
  echo
)

while getopts ":i:w:r:" opt; do
  case $opt in
    i)
      iteration=$OPTARG
      ;;
    w)
      work_duration=$OPTARG
      ;;
    r)
      rest_duration=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

echo "Iteration: $iteration"
echo "Work duration: $work_duration m"
echo "Rest duration: $rest_duration m"

for ((i=1; i<=$iteration - 1; i++))
do
    echo "Iteration $i" 
    echo "Work"
    countdown $(( $work_duration * 60))
    osascript -e 'display notification "Time to take a break" with title "Break"'
    echo "Rest"
    countdown $(( $rest_duration * 60))
    osascript -e 'display notification "Time to get back to work" with title "Work"'
done

echo "Last iteration" 
echo "Work"
countdown $(( $work_duration * 60))
osascript -e 'display notification "Time to take a long break" with title "Done :)"'
