#!/bin/bash
iteration=3
work_duration=25
rest_duration=5
multiplier=1

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     multiplier=1;;
    Darwin*)    multiplier=60;;
    *)          machine="check usage of sleep command and specify under m flag"
esac

while getopts ":i:w:r:m:" opt; do
  case $opt in
    i)
      iteration=$OPTARG
      ;;
    w)
      work_duration=$OPTARG
      ;;
    r)
      rest_duration=$OPTARG
      ;;
    m)
      multiplier=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

echo "Iteration: $iteration"
echo "Work duration: $work_duration m"
echo "Rest duration: $rest_duration m"

work_duration=$(($work_duration * $multiplier))
rest_duration=$(($rest_duration * $multiplier))

for ((i=1; i<=$iteration; i++))
do
    echo "Iteration $i"
    sleep "$work_duration"m
    osascript -e 'display notification "Time to take a break" with title "Break"'
    sleep "$rest_duration"m
    osascript -e 'display notification "Time to get back to work" with title "Work"'
done
osascript -e 'display notification "Time to take a long break" with title "Done :)"'
