#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
   else 
   echo "$1"
   git commit -am "$1"
fi
branch=`git status | head -1 |  sed "s/.*On branch //"`
git push origin $branch
echo $branch 